### PR TITLE
fix: changedelete symbol with linematch enabled

### LINKED ISSUE #701: some linematch hunks need topdelete
### Description

image

There are no signs for the bottom hunk since the modified position is taking its place.

### PR DESCRIPTION
**Pull request by clktmr**
Since linematch will report a changed line following deleted lines as multiple hunks on a single line, it will only show the `changed` sign and will drop the `deleted` sign.  To fix this check for overlapping hunks and mark the change hunk as changedelete.

Fixes #701 in part

### CODE REVIEW

File: lua/gitsigns/manager.lua [hunk 1]
```diff
@@ -41,16 +41,24 @@ local function apply_win_signs0(bufnr, signs, hunks, top, bot, clear, untracked)
...
+        (hunk.type == "change" and next.type == "delete") and
+        (hunk.added.start + hunk.added.count - 1 == next.added.start)
+
     -- To stop the sign column width changing too much, if there are signs to be
     -- added but none of them are visible in the window, then make sure to add at
     -- least one sign. Only do this on the first call after an update when we all
     -- the signs have been cleared.
     if clear and i == 1 then
-      signs:add(bufnr, gs_hunks.calc_signs(hunk, hunk.added.start, hunk.added.start, untracked))
+      signs:add(bufnr, gs_hunks.calc_signs(hunk, hunk.added.start, hunk.added.start, untracked, changedelete))
```
Comment (lewis6991) [inline lua/gitsigns/manager.lua:57]: Would it be better to pass in `next`?

Comment (clktmr) [reply lua/gitsigns/manager.lua:57]: It felt consistent this way because untracked is also passed in. On the other hand it would put the actual sign calculation in calc_signs. Give me a moment, I'll change it

**Comment by clktmr** [comment]
BTW I think the default sign for 'changedelete' is a bit unfortunate. For me using a blend of change and delete is more intuitive. Are you open to change the default icons? I would recommend
```
delete = { text = ' ▁' },
topdelete = { text = ' ▔' },
changedelete = { text = '┃▁' },
```
This puts delete and topdelete on the second char of the sign, and changedelete is just a combination of both.

File: lua/gitsigns/manager.lua (hunk 1 above)
Comment (clktmr) [reply lua/gitsigns/manager.lua]: Done

**Comment by lewis6991** [comment]
> For me using a blend of change and delete is more intuitive. Are you open to change the default icons? I would recommend

Ideally, every hunk should get it's own sign. For changedelete, I think it would be better to use `change` and `topdelete`.
