### PR TITLE
fix: sort get_nav_hunks to handle mixed hunk states

### LINKED ISSUE #1113: nav_hunk with opts { target = 'all' } does not handle files with mixed hunks
### Description

nav_hunk with opts { target = 'all' } does not handle files with mixed staged and unstaged hunks. If you have 4 hunks staged and 2 hunks unstaged, it will only jump between the first 2 hunks in the file, staged or not. 

### Neovim version

0.10.1

### Operating system and version

Nixos 24.05

### Expected behavior

Jump between all 6 hunks, staged or not

### Actual behavior

Jumped between first 2 hunks in file, one unstaged and one staged

### Minimal config

```Lua
for name, url in pairs{
  gitsigns = 'https://github.com/lewis6991/gitsigns.nvim',
} do
  local install_path = vim.fn.fnamemodify('gitsigns_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    vim.fn.system { 'git', 'clone', '--depth=1', url, install_path }
  end
  vim.opt.runtimepath:append(install_path)
end

local gs = require("gitsigns")
gs.setup{
  debug_mode = true, -- You must add this to enable debug messages
  on_attach = function ()
    vim.keymap.set('n', ']g', function()
      gs.next_hunk({target = 'all'})
    end)
    vim.keymap.set('n', '[g', function()
      gs.prev_hunk({target = 'all'})
    end)
  end
}
```

### Steps to reproduce

Prereq: setup nvim with above minimal config.

1. `mkdir gitsigns_issue`
2. `cd gitsigns_issue`
3. `git init`
4. `echo "hunk1" >> file`
5. `git add file`
6. `echo "hunk2" >> file`
7 `nvim file` and observe that ]g and [g don't work between both hunks

### Gitsigns debug messages

_No response_

### Gitsigns cache

_No response_

### PR DESCRIPTION
**Pull request by iofq**
Fixes #1113

`gitsigns.hunks.find_nearest_hunk`'s algorithm only works on a sorted list of hunks (because it returns `i+1` which it assumes is the next hunk), however `get_nav_hunks` did not return the list of hunks sorted.

So `get_nav_hunks` might return a list with lines 16, 29, 24 (staged hunks appended to unstaged); then when jumping from 16 to the next hunk, it would find and jump to 29 when you would expect it to find the hunk at line 24.

I'm not familiar with the codebase, but this does not look like it will break anything else. `find_nearest_hunk` is only used in `nav_hunk`.

### CODE REVIEW

File: lua/gitsigns/actions.lua [hunk 1]
```diff
@@ -573,6 +573,9 @@ local function get_nav_hunks(bufnr, target, greedy)
       hunks = hunks_head
     end
   end
+  table.sort(hunks, function(h1, h2)
```
Comment (lewis6991) [inline lua/gitsigns/actions.lua:576]: I think this can moved to below line 571.

Comment (iofq) [reply lua/gitsigns/actions.lua]: makes sense, updated
